name: Gradle build with docs

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    
    steps:
      - name: Setup JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Make gradle wrapper executable
        run: chmod +x ./gradlew

      # We could do it all in one step, if we wanted to:
#       run: ./gradlew build
        
      - name: Build the code and produce Javadoc
        run: ./gradlew build -x test

#     - name: Generate Javadoc
#       run: |
#         ./gradlew generateJavadoc

      # Upload the Javadoc to save having to generate it again later.
      - name: Upload Javadoc artifact
        if: github.ref == 'refs/heads/main' # We will only publish to GitHub pages if its a push to main
        uses: actions/upload-artifact@v3
        with:
          name: javadoc
          path: ${{ github.workspace }}/build/docs/javadoc/**/*
          if-no-files-found: error # 'warn' or 'ignore' are also available, defaults to `warn`
          retention-days: 60

      # Run the tests
      - name: Run Tests
        run: ./gradlew clean test
  
  publish-javadoc:
    name: Publish Javadoc to GitHub pages
    needs: build
    if: github.ref == 'refs/heads/main' # We will only publish to GitHub pages if its a push to main

    runs-on: ubuntu-latest
    timeout-minutes: 5
   
    environment:
      name: github-pages
      url: 'https://ronanj2.github.io/Logbook2/'
    
    steps:
#     - name: Setup JDK 17
#       uses: actions/setup-java@v2
#       with:
#         java-version: '17'
#         distribution: 'adopt'
#     
#     - name: Check our code
#       uses: actions/checkout@v2
#       
#     - name: Make gradle wrapper executable
#       run: chmod +x ./gradlew
#     
#     - name: Generate Javadoc
#       run: |
#         ./gradlew generateJavadoc

      - uses: actions/download-artifact@v3
        with:
          name: javadoc
          path: ${{ github.workspace }}/javadoc/

      # Publish Javadoc to GitHub pages (branch gh-pages)
      - name: Publish JavaDoc to GitHub pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./javadoc
