name: Gradle build with docs

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Setup JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Check our code
        uses: actions/checkout@v2
        
      # Make gradle wrapper executable
      - name: Make gradlew executable
        run: chmod +x ./gradlew
        
      # Build the code
      - name: Build
        run: ./gradlew build -x test

      # Run the tests
      - name: Run Tests
        run: ./gradlew clean test

      # Generate Javadoc
      - name: Run Tests
        run: ./gradlew generateJavadoc

      # Publish Javadoc to GitHub pages (branch gh-pages)
      - name: Publish JavaDoc to GitHub pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/docs/javadoc