name: Gradle build with docs

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Setup JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Check our code
        uses: actions/checkout@v2
        
      # Make gradle wrapper executable
      - name: Make gradlew executable
        run: chmod +x ./gradlew
        
      # Build the code
      - name: Build
        run: ./gradlew build -x test

      - name: Run Tests
        run: ./gradlew clean test

      - name: Generate Javadoc
        run: ./gradlew generateJavadoc

      # Build, test and create Javadoc
      #- name: Build
      #  run: ./gradlew build

      - uses: actions/upload-artifact@v3
        with:
          name: backend-package
          path: ${{ github.workspace }}/**/*
          if-no-files-found: error # 'warn' or 'ignore' are also available, defaults to `warn`
          retention-days: 1 # Set low because I want to stay inside the limits of the free tier.

      # Publish Javadoc to GitHub pages (branch gh-pages)
      - name: Publish JavaDoc to GitHub pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/docs/javadoc