name: Gradle build with docs

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Setup JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Check our code
        uses: actions/checkout@v2
        
      # Make gradle wrapper executable
      - name: Make gradlew executable
        run: chmod +x ./gradlew
        
      # Run the build using gradle
      - name: Building with Gradle
        run: ./gradlew build